### ISSUE TITLE
Host Django App online

### ISSUE THREAD

**Issue by sean-meade** [sean-meade/fund-frontier#5]
As a user I would like to access the web app from anywhere
so that I can evaluate projects from anywhere

**Comment by Parham-Mehrabi** [comment]
good day to you Sean,
you need to host your project in a server,
there are two options for you:
1. paas
2. saas
if you are not familiar with server consepts you can use a provider who give you a GUI panel and you can easly deploy your project
otherwise you need to host it yourself in a server using Nginx + Gunicorn
